server:
  port: 8081
spring:
  security:
    oauth2:
      client:
        provider:
          custom:
            token-uri: http://localhost:8080/oauth/token
        registration:
          custom:
            client-id: campaign-station-client
            client-secret: password
            scope: "*"
            authorization-grant-type: client_credentials
  cloud:
    gateway:
      routes:
        - id: sql_admin_localhost_id
          uri: http://localhost:8888/
          predicates:
            - Path=/sqladminlocalhost/**
          filters:
            - RewritePath=/sqladminlocalhost/(?<segment>.*), /$\{segment}
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
#            - MyFilter