server:
  port: 8081

spring:
  application:
    name: gateway
  security:
    oauth2:
      client:
        registration:
          gateway-password:
            provider: okta
            client-id: campaign-station-client
            client-secret: password
            authorization-grant-type: password
            scope: "*"
#          gateway-client-creds:
#            provider: okta
#            client-id: {yourClientId}
#            client-secret: {yourSecret}
#            authorization-grant-type: client_credentials
#            scope: my_scope
        provider:
          okta:
            token-uri: http://localhost:8080/oauth/token
  cloud:
    gateway:
      routes:
        - id: sql_admin_localhost_id
          uri: http://localhost:8888/
          predicates:
            - Path=/sqladminlocalhost/**
          filters:
            - RewritePath=/sqladminlocalhost/(?<segment>.*), /$\{segment}
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
#  cloud:
#    gateway:
#      routes:
#      - id: resource
#        uri: http://resource:9000/**
#        predicates:
#          - Host=**.nx.com
#          - Method=GET,POST
#          - Path=/service/**
#        filters:
#          - StripPrefix=1
#          - RemoveRequestHeader=Cookie
#          - name: Retry
#            args:
#              retries: 5
#              series: SERVER_ERROR
#              methods: GET,POST
#              backoff:
#                firstBackoff: 10ms
#                maxBackoff: 50ms
#                factor: 2
#                basedOnPreviousValue: false
##      httpserver:
##        wiretap: true
##      httpclient:
##        wiretap: true
#
#
#client-registration-id: gateway-client-creds
#
#logging:
#  level:
#    root: INFO
#    org.springframework.web: TRACE
#    org.springframework.web.HttpLogging: TRACE
#    org.springframework.security: TRACE
#    org.springframework.security.oauth2: TRACE
#    org.springframework.cloud.gateway: TRACE
#
#
# actuator-related configuration
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
